### ISSUE TITLE
Sync labels script fails to add new labels

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/sync-github-labels#9]
Attempting to create and update new labels in repository fails:
```
$ ./sync_labels.py DataBiosphere/azul DataBiosphere/sync-github-labels
==============================
sync_labels.py: Syncing labels from DataBiosphere/azul to DataBiosphere/sync-github-labels
The following labels will be created in DataBiosphere/sync-github-labels:
 [+] ES
 [+] base
 [+] chained
 [+] operator
The following labels will be updated in DataBiosphere/sync-github-labels:
 [u] 0 reviews
 [u] 1 review
 [u] 2 reviews
 [u] 3 reviews
 [u] 4+ reviews
 [u] API
 [u] DCP/1
 [u] WIP
 [u] authentication
 [u] authorization
 [u] blocked
 [u] bug
 [u] canary
 [u] code
 [u] critical
 [u] data
 [u] dcp demo
 [u] dcp demoed
 [u] debt
 [u] demo
 [u] demo blocked
 [u] demoed
 [u] dependencies
 [u] do not promote
 [u] doc
 [u] duplicate
 [u] easy
 [u] enh
 [u] epic
 [u] expected
 [u] facets
 [u] gitlab
 [u] hold warm
 [u] hotfix
 [u] indexer
 [u] infra
 [u] invalid
 [u] manifests
 [u] needs info
 [u] needs port
 [u] no demo
 [u] no pr
 [u] no sandbox
 [u] orange
 [u] partial
 [u] perf
 [u] port
 [u] question
 [u] reindex
 [u] reindex sandbox
 [u] reqs
 [u] sandbox
 [u] security
 [u] service
 [u] spike:1
 [u] spike:2
 [u] spike:3
 [u] spike:5
 [u] spike:8
 [u] stub
 [u] task
 [u] test
 [u] thereifixedit
 [u] upgrade
 [u] urgent
 [u] wontfix
 [u] workaround
Error adding label: operator
Traceback (most recent call last):
  File "./sync_labels.py", line 75, in sync_labels
    function(name, src, dst)
  File "./sync_labels.py", line 91, in add_label
    dst.create_label(name, color, description)
  File "/Users/abrahamchavez/PycharmProjects/sync-github-labels/.venv/lib/python3.8/site-packages/github/Repository.py", line 1231, in create_label
    headers, data = self._requester.requestJsonAndCheck(
  File "/Users/abrahamchavez/PycharmProjects/sync-github-labels/.venv/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/Users/abrahamchavez/PycharmProjects/sync-github-labels/.venv/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/issues#create-a-label"}
```

**Comment by achave11-ucsc** [comment]
This is a non-issue, `GITHUB_API_KEY` didn't have appropriate permissions.
